[build]
  publish = "public"
  command = "npm run build:emb && npm run build:site"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Optional pretty redirects
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/recommend"
  status = 200
